=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/project/src/main/resources/org/babyfishdemo/war3shop/db/installer/schema/table.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:tns="http://www.babyfishdemo.org/war3shop/db-installer" 
targetNamespace="http://www.babyfishdemo.org/war3shop/db-installer" 
elementFormDefault="qualified" 
attributeFormDefault="unqualified">
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="schema">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="primary-key">
                                <xs:complexType>
                                    <xs:group ref="tns:columnOrForeignKey" maxOccurs="unbounded"/>
                                    <xs:attribute name="sequence" type="tns:nameType" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="column" type="tns:columnType"/>
                                <xs:element name="unique">
                                    <xs:complexType>
                                        <xs:group ref="tns:columnOrForeignKey" maxOccurs="unbounded"/>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element ref="tns:foreign-key"/>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="columnNameUnique">
                        <xs:selector xpath=".//tns:column"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="data" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="row" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:anyAttribute processContents="lax"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="tns:nameType" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="columnOrForeignKey">
        <xs:choice>
            <xs:element name="column" type="tns:columnType"/>
            <xs:element ref="tns:foreign-key"/>
        </xs:choice>
    </xs:group>
    <xs:element name="foreign-key">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="column" type="tns:foreignKeyColumnType" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="reference" type="tns:nameType" use="required"/>
        </xs:complexType>
        <xs:unique name="referenceColumnNameUnique">
            <xs:selector xpath="./tns:column"/>
            <xs:field xpath="@reference"/>
        </xs:unique>
    </xs:element>
    <xs:complexType name="columnType">
        <xs:attribute name="name" type="tns:nameType" use="required"/>
        <xs:attribute name="type" type="tns:typeType" use="required"/>
    </xs:complexType>
    <xs:complexType name="foreignKeyColumnType">
        <xs:complexContent>
            <xs:extension base="tns:columnType">
                <xs:attribute name="reference" type="tns:nameType" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="typeType">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="(boolean|int|long|decimal|date|timestamp|clob|blob)\??"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="(string|binary)\[\d+\]\??"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
</xs:schema>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/manufacturer_purchaser_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<table name="manufacturer_purchaser_mapping" 
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key>
            <foreign-key reference="manufacturer">
                <column name="manufacturer_id" type="long"/>
            </foreign-key>
            <foreign-key reference="user">
                <column name="purchaser_id" type="long"/>
            </foreign-key>
        </primary-key>
    </schema>
    <data>
        <row manufacturer_id="11" purchaser_id="6"/>
        <row manufacturer_id="12" purchaser_id="6"/>
        <row manufacturer_id="13" purchaser_id="6"/>
        <row manufacturer_id="14" purchaser_id="6"/>
        <row manufacturer_id="15" purchaser_id="6"/>
        <row manufacturer_id="16" purchaser_id="6"/>
        <row manufacturer_id="17" purchaser_id="6"/>
        <row manufacturer_id="18" purchaser_id="6"/>
        <row manufacturer_id="19" purchaser_id="6"/>
        <row manufacturer_id="1" purchaser_id="6"/>
        <row manufacturer_id="2" purchaser_id="6"/>
        <row manufacturer_id="3" purchaser_id="6"/>
        <row manufacturer_id="32" purchaser_id="6"/>
        <row manufacturer_id="33" purchaser_id="6"/>
        <row manufacturer_id="34" purchaser_id="6"/>
        <row manufacturer_id="26" purchaser_id="6"/>
        <row manufacturer_id="27" purchaser_id="6"/>
        <row manufacturer_id="28" purchaser_id="6"/>
        
        <row manufacturer_id="1" purchaser_id="7"/>
        <row manufacturer_id="2" purchaser_id="7"/>
        <row manufacturer_id="3" purchaser_id="7"/>
        <row manufacturer_id="4" purchaser_id="7"/>
        <row manufacturer_id="5" purchaser_id="7"/>
        <row manufacturer_id="6" purchaser_id="7"/>
        <row manufacturer_id="7" purchaser_id="7"/>
        <row manufacturer_id="8" purchaser_id="7"/>
        <row manufacturer_id="9" purchaser_id="7"/>     
        <row manufacturer_id="10" purchaser_id="7"/>
        <row manufacturer_id="29" purchaser_id="7"/>
        <row manufacturer_id="30" purchaser_id="7"/>
        <row manufacturer_id="31" purchaser_id="7"/>
        <row manufacturer_id="23" purchaser_id="7"/>
        <row manufacturer_id="24" purchaser_id="7"/>
        <row manufacturer_id="25" purchaser_id="7"/>
        <row manufacturer_id="17" purchaser_id="7"/>
        <row manufacturer_id="18" purchaser_id="7"/>
        <row manufacturer_id="19" purchaser_id="7"/>
        
        <row manufacturer_id="29" purchaser_id="8"/>
        <row manufacturer_id="30" purchaser_id="8"/>
        <row manufacturer_id="31" purchaser_id="8"/>
        <row manufacturer_id="32" purchaser_id="8"/>
        <row manufacturer_id="33" purchaser_id="8"/>
        <row manufacturer_id="34" purchaser_id="8"/>
        <row manufacturer_id="35" purchaser_id="8"/>
        <row manufacturer_id="36" purchaser_id="8"/>
        <row manufacturer_id="37" purchaser_id="8"/>
        <row manufacturer_id="20" purchaser_id="8"/>
        <row manufacturer_id="21" purchaser_id="8"/>
        <row manufacturer_id="22" purchaser_id="8"/>
        <row manufacturer_id="14" purchaser_id="8"/>
        <row manufacturer_id="15" purchaser_id="8"/>
        <row manufacturer_id="16" purchaser_id="8"/>
        <row manufacturer_id="8" purchaser_id="8"/>
        <row manufacturer_id="9" purchaser_id="8"/>
        <row manufacturer_id="10" purchaser_id="8"/>
        
        <row manufacturer_id="20" purchaser_id="9"/>
        <row manufacturer_id="21" purchaser_id="9"/>
        <row manufacturer_id="22" purchaser_id="9"/>
        <row manufacturer_id="23" purchaser_id="9"/>
        <row manufacturer_id="24" purchaser_id="9"/>
        <row manufacturer_id="25" purchaser_id="9"/>
        <row manufacturer_id="26" purchaser_id="9"/>
        <row manufacturer_id="27" purchaser_id="9"/>
        <row manufacturer_id="28" purchaser_id="9"/>
        <row manufacturer_id="11" purchaser_id="9"/>
        <row manufacturer_id="12" purchaser_id="9"/>
        <row manufacturer_id="13" purchaser_id="9"/>
        <row manufacturer_id="4" purchaser_id="9"/>
        <row manufacturer_id="5" purchaser_id="9"/>
        <row manufacturer_id="6" purchaser_id="9"/>
        <row manufacturer_id="35" purchaser_id="9"/>
        <row manufacturer_id="36" purchaser_id="9"/>
        <row manufacturer_id="37" purchaser_id="9"/>
        
        <row manufacturer_id="38" purchaser_id="10"/>
        <row manufacturer_id="39" purchaser_id="10"/>
        <row manufacturer_id="40" purchaser_id="10"/>
        <row manufacturer_id="41" purchaser_id="10"/>
        <row manufacturer_id="10" purchaser_id="10"/>
        <row manufacturer_id="19" purchaser_id="10"/>
        <row manufacturer_id="28" purchaser_id="10"/>
        <row manufacturer_id="37" purchaser_id="10"/>
        
        <row manufacturer_id="10" purchaser_id="2"/>
        <row manufacturer_id="19" purchaser_id="2"/>
        <row manufacturer_id="28" purchaser_id="2"/>
        <row manufacturer_id="37" purchaser_id="2"/>
        <row manufacturer_id="38" purchaser_id="6"/>
        <row manufacturer_id="39" purchaser_id="6"/>
        <row manufacturer_id="40" purchaser_id="6"/>
        <row manufacturer_id="41" purchaser_id="6"/>
    </data>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/order_item.xml
<?xml version="1.0"?>
<table 
name="order_item"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key sequence="order_item_id_seq">
            <column name="order_item_id" type="long"/>
        </primary-key>
        <foreign-key reference="order">
            <column name="order_id" type="long"/>
        </foreign-key>
        <foreign-key reference="product">
            <column name="product_id" type="long"/>
        </foreign-key>
        <column name="instant_unit_price" type="decimal"/>
        <column name="quantity" type="int"/>
        <column name="total_expected_money" type="decimal"/>
        <column name="total_reduced_money" type="decimal"/>
        <column name="total_gift_money" type="decimal"/>
        <column name="total_actual_money" type="decimal"/>
    </schema>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/product_manufacturer_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<table name="product_manufacturer_mapping" 
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key>
            <foreign-key reference="product">
                <column name="product_id" type="long"/>
            </foreign-key>
            <foreign-key reference="manufacturer">
                <column name="manufacturer_id" type="long"/>
            </foreign-key>
        </primary-key>
    </schema>
    <data>
        <row product_id="1" manufacturer_id="10"/>
        <row product_id="2" manufacturer_id="10"/>
        <row product_id="3" manufacturer_id="10"/>
        <row product_id="4" manufacturer_id="10"/>
        <row product_id="5" manufacturer_id="28"/>
        <row product_id="6" manufacturer_id="28"/>
        <row product_id="7" manufacturer_id="28"/>
        <row product_id="8" manufacturer_id="28"/>
        <row product_id="9" manufacturer_id="19"/>
        <row product_id="10" manufacturer_id="19"/>
        <row product_id="11" manufacturer_id="19"/>
        <row product_id="12" manufacturer_id="19"/>
        <row product_id="13" manufacturer_id="37"/>
        <row product_id="14" manufacturer_id="37"/>
        <row product_id="15" manufacturer_id="37"/>
        <row product_id="16" manufacturer_id="37"/>
        <row product_id="17" manufacturer_id="38"/>
        <row product_id="18" manufacturer_id="38"/>
        <row product_id="19" manufacturer_id="38"/>
        <row product_id="20" manufacturer_id="38"/>
        <row product_id="21" manufacturer_id="38"/>
        <row product_id="22" manufacturer_id="38"/>
        <row product_id="23" manufacturer_id="38"/>
        <row product_id="24" manufacturer_id="38"/>
        <row product_id="25" manufacturer_id="1"/>
        <row product_id="25" manufacturer_id="2"/>
        <row product_id="25" manufacturer_id="3"/>
        <row product_id="26" manufacturer_id="4"/>
        <row product_id="27" manufacturer_id="4"/>
        <row product_id="28" manufacturer_id="4"/>
        <row product_id="29" manufacturer_id="5"/>
        <row product_id="30" manufacturer_id="5"/>
        <row product_id="31" manufacturer_id="5"/>
        <row product_id="32" manufacturer_id="5"/>
        <row product_id="33" manufacturer_id="7"/>
        <row product_id="34" manufacturer_id="8"/>
        <row product_id="35" manufacturer_id="6"/>
        <row product_id="36" manufacturer_id="6"/>
        <row product_id="37" manufacturer_id="11"/>
        <row product_id="37" manufacturer_id="12"/>
        <row product_id="37" manufacturer_id="13"/>
        <row product_id="38" manufacturer_id="11"/>
        <row product_id="38" manufacturer_id="12"/>
        <row product_id="38" manufacturer_id="13"/>
        <row product_id="39" manufacturer_id="14"/>
        <row product_id="40" manufacturer_id="14"/>
        <row product_id="41" manufacturer_id="14"/>
        <row product_id="42" manufacturer_id="15"/>
        <row product_id="43" manufacturer_id="15"/>
        <row product_id="44" manufacturer_id="15"/>
        <row product_id="45" manufacturer_id="16"/>
        <row product_id="46" manufacturer_id="16"/>
        <row product_id="47" manufacturer_id="16"/>
        <row product_id="48" manufacturer_id="17"/>
        <row product_id="49" manufacturer_id="17"/>
        <row product_id="50" manufacturer_id="29"/>
        <row product_id="50" manufacturer_id="30"/>
        <row product_id="50" manufacturer_id="31"/>
        <row product_id="51" manufacturer_id="32"/>
        <row product_id="52" manufacturer_id="32"/>
        <row product_id="53" manufacturer_id="32"/>
        <row product_id="54" manufacturer_id="32"/>
        <row product_id="55" manufacturer_id="33"/>
        <row product_id="56" manufacturer_id="33"/>
        <row product_id="57" manufacturer_id="33"/>
        <row product_id="58" manufacturer_id="34"/>
        <row product_id="59" manufacturer_id="34"/>
        <row product_id="60" manufacturer_id="34"/>
        <row product_id="61" manufacturer_id="34"/>
        <row product_id="62" manufacturer_id="35"/>
        <row product_id="63" manufacturer_id="20"/>
        <row product_id="63" manufacturer_id="21"/>
        <row product_id="63" manufacturer_id="22"/>
        <row product_id="64" manufacturer_id="23"/>
        <row product_id="65" manufacturer_id="23"/>
        <row product_id="66" manufacturer_id="23"/>
        <row product_id="67" manufacturer_id="24"/>
        <row product_id="68" manufacturer_id="24"/>
        <row product_id="69" manufacturer_id="24"/>
        <row product_id="70" manufacturer_id="25"/>
        <row product_id="71" manufacturer_id="25"/>
        <row product_id="72" manufacturer_id="25"/>
        <row product_id="73" manufacturer_id="26"/>
        <row product_id="74" manufacturer_id="27"/>
        <row product_id="75" manufacturer_id="39"/>
        <row product_id="76" manufacturer_id="39"/>
        <row product_id="77" manufacturer_id="39"/>
        <row product_id="77" manufacturer_id="18"/>
        <row product_id="77" manufacturer_id="9"/>
        <row product_id="77" manufacturer_id="36"/>
        <row product_id="77" manufacturer_id="27"/>
        <row product_id="78" manufacturer_id="36"/>
        <row product_id="79" manufacturer_id="18"/>
        <row product_id="80" manufacturer_id="18"/>
        <row product_id="80" manufacturer_id="36"/>
        <row product_id="80" manufacturer_id="27"/>
        <row product_id="81" manufacturer_id="18"/>
        <row product_id="82" manufacturer_id="27"/>
        <row product_id="83" manufacturer_id="9"/>
        <row product_id="84" manufacturer_id="18"/>
        <row product_id="85" manufacturer_id="36"/>
        <row product_id="86" manufacturer_id="27"/>
        <row product_id="87" manufacturer_id="41"/>
        <row product_id="88" manufacturer_id="39"/>
        <row product_id="89" manufacturer_id="41"/>
        <row product_id="90" manufacturer_id="41"/>
        <row product_id="91" manufacturer_id="18"/>
        <row product_id="91" manufacturer_id="9"/>
        <row product_id="91" manufacturer_id="36"/>
        <row product_id="91" manufacturer_id="27"/>
        <row product_id="92" manufacturer_id="39"/>
        <row product_id="93" manufacturer_id="39"/>
        <row product_id="94" manufacturer_id="18"/>
        <row product_id="94" manufacturer_id="9"/>
        <row product_id="94" manufacturer_id="36"/>
        <row product_id="94" manufacturer_id="27"/>
        <row product_id="95" manufacturer_id="9"/>
        <row product_id="96" manufacturer_id="9"/>
        <row product_id="97" manufacturer_id="39"/>
        <row product_id="97" manufacturer_id="9"/>
        <row product_id="98" manufacturer_id="39"/>
        <row product_id="99" manufacturer_id="18"/>
        <row product_id="100" manufacturer_id="36"/>
        <row product_id="101" manufacturer_id="39"/>
        <row product_id="101" manufacturer_id="18"/>
        <row product_id="101" manufacturer_id="9"/>
        <row product_id="101" manufacturer_id="36"/>
        <row product_id="101" manufacturer_id="27"/>
        <row product_id="102" manufacturer_id="27"/>
        <row product_id="103" manufacturer_id="18"/>
        <row product_id="104" manufacturer_id="39"/>
        <row product_id="105" manufacturer_id="36"/>
        <row product_id="106" manufacturer_id="39"/>
        <row product_id="107" manufacturer_id="40"/>
        <row product_id="108" manufacturer_id="40"/>
        <row product_id="109" manufacturer_id="40"/>
    </data>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/role_privilege_mapping.xml
<?xml version="1.0"?>
<table 
name="role_privilege_mapping"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key>
            <foreign-key reference="role">
                <column name="role_id" type="long"/>
            </foreign-key>
            <foreign-key reference="privilege">
                <column name="privilege_id" type="long"/>
            </foreign-key>
        </primary-key>
    </schema>
    <data>
        <row role_id="1" privilege_id="1"/>
        <row role_id="1" privilege_id="2"/>
        <row role_id="1" privilege_id="3"/>
        <row role_id="2" privilege_id="4"/>
        <row role_id="3" privilege_id="5"/>
        <row role_id="4" privilege_id="6"/>
    </data>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/temporary_uploaded_file.xml
<?xml version="1.0"?>
<table 
name="temporary_uploaded_file"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key sequence="temporary_uploaded_file_id_seq">
            <column name="temporary_uploaded_file_id" type="long"/>
        </primary-key>
        <column name="gc_threshold" type="timestamp"/>
        <column name="mime_type" type="string[20]"/>
        <column name="key" type="string[20]"/>
        <column name="content" type="blob"/>
    </schema>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/privilege.xml
<?xml version="1.0"?>
<table 
name="privilege"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key sequence="privilege_id_seq">
            <column name="privilege_id" type="long"/>
        </primary-key>
        <column name="version" type="int"/>
        <unique>
            <column name="name" type="string[50]"/>
        </unique>
    </schema>
    <data>
        <row
            privilege_id="1"
            version="1"
            name="manage-manufacturers"/>
        <row
            privilege_id="2"
            version="1"
            name="manage-products"/>
        <row
            privilege_id="3"
            version="1"
            name="manage-preferentials"/>
        <row
            privilege_id="4"
            version="1"
            name="purchase-products"/>
        <row
            privilege_id="5"
            version="1"
            name="manage-orders"/>
        <row
            privilege_id="6"
            version="1"
            name="delivery-orders"/>
    </data>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/alarm.xml
<?xml version="1.0"?>
<table 
name="alarm"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key sequence="alarm_id_seq">
            <column name="alarm_id" type="long"/>
        </primary-key>
        <column name="version" type="int"/>
        <column name="creation_time" type="timestamp"/>
        <column name="message" type="string[400]"/>
        <column name="acknowledged" type="boolean"/>
        <foreign-key reference="user">
            <column name="user_id" type="long"/>
        </foreign-key>
    </schema>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/gift_item.xml
<?xml version="1.0"?>
<table 
name="gift_item"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key sequence="gift_item_id_seq">
            <column name="gift_item_id" type="long"/>
        </primary-key>
        <foreign-key reference="order">
            <column name="order_id" type="long"/>
        </foreign-key>
        <foreign-key reference="product">
            <column name="product_id" type="long"/>
        </foreign-key>
        <column name="instant_unit_price" type="decimal"/>
        <column name="quantity" type="int"/>
    </schema>
</table>
