=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/project/src/main/resources/org/babyfishdemo/war3shop/db/installer/schema/table.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:tns="http://www.babyfishdemo.org/war3shop/db-installer" 
targetNamespace="http://www.babyfishdemo.org/war3shop/db-installer" 
elementFormDefault="qualified" 
attributeFormDefault="unqualified">
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="schema">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="primary-key">
                                <xs:complexType>
                                    <xs:group ref="tns:columnOrForeignKey" maxOccurs="unbounded"/>
                                    <xs:attribute name="sequence" type="tns:nameType" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="column" type="tns:columnType"/>
                                <xs:element name="unique">
                                    <xs:complexType>
                                        <xs:group ref="tns:columnOrForeignKey" maxOccurs="unbounded"/>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element ref="tns:foreign-key"/>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:unique name="columnNameUnique">
                        <xs:selector xpath=".//tns:column"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
                <xs:element name="data" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="row" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:anyAttribute processContents="lax"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="tns:nameType" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="columnOrForeignKey">
        <xs:choice>
            <xs:element name="column" type="tns:columnType"/>
            <xs:element ref="tns:foreign-key"/>
        </xs:choice>
    </xs:group>
    <xs:element name="foreign-key">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="column" type="tns:foreignKeyColumnType" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="reference" type="tns:nameType" use="required"/>
        </xs:complexType>
        <xs:unique name="referenceColumnNameUnique">
            <xs:selector xpath="./tns:column"/>
            <xs:field xpath="@reference"/>
        </xs:unique>
    </xs:element>
    <xs:complexType name="columnType">
        <xs:attribute name="name" type="tns:nameType" use="required"/>
        <xs:attribute name="type" type="tns:typeType" use="required"/>
    </xs:complexType>
    <xs:complexType name="foreignKeyColumnType">
        <xs:complexContent>
            <xs:extension base="tns:columnType">
                <xs:attribute name="reference" type="tns:nameType" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z_][A-Za-z0-9_]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="typeType">
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="(boolean|int|long|decimal|date|timestamp|clob|blob)\??"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="(string|binary)\[\d+\]\??"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
</xs:schema>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/variable.xml
<?xml version="1.0"?>
<table 
name="variable"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key>
            <column name="name" type="string[30]"/>
        </primary-key>
        <column name="value" type="string[100]?"/>
        <column name="encrypted_value" type="binary[256]?"/>
    </schema>
    <data>
        <row 
            name="sys.email.protocol"
            value="${sys.email.protocol}"/>
        <row 
            name="sys.email.host"
            value="${sys.email.host}"/>
        <row
            name="sys.email.ssl"
            value="${sys.email.ssl}"/>
        <row 
            name="sys.email.port"
            value="${sys.email.port}"/>
        <row 
            name="sys.email.user"
            value="${sys.email.user}"/>
        <row 
            name="*sys.email.password"
            encrypted_value="rsa(${*sys.email.password})"/>
    </data>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/purchasing.xml
<?xml version="1.0"?>
<table 
name="purchasing"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key sequence="purchasing_id_seq">
            <column name="purchasing_id" type="long"/>
        </primary-key>
        <foreign-key reference="user">
            <column name="purchaser_id" type="long"/>
        </foreign-key>
        <column name="creation_time" type="timestamp"/>
        <column name="total_purchased_price" type="decimal"/>
    </schema>
    <data>
        <row
            purchasing_id="1"
            purchaser_id="2"
            creation_time="-100*24*60*60*1000"
            total_purchased_price="495000"/>
        <row
            purchasing_id="2"
            purchaser_id="2"
            creation_time="-99*24*60*60*1000"
            total_purchased_price="412500"/>
        <row
            purchasing_id="3"
            purchaser_id="2"
            creation_time="-98*24*60*60*1000"
            total_purchased_price="412500"/>
        <row
            purchasing_id="4"
            purchaser_id="6"
            creation_time="-100*24*60*60*1000"
            total_purchased_price="2247000"/>
        <row
            purchasing_id="5"
            purchaser_id="6"
            creation_time="-99*24*60*60*1000"
            total_purchased_price="3261000"/>
        <row
            purchasing_id="6"
            purchaser_id="6"
            creation_time="-98*24*60*60*1000"
            total_purchased_price="3145500"/>
        <row
            purchasing_id="7"
            purchaser_id="7"
            creation_time="-100*24*60*60*1000"
            total_purchased_price="1786500"/>
        <row
            purchasing_id="8"
            purchaser_id="7"
            creation_time="-99*24*60*60*1000"
            total_purchased_price="2041500"/>
        <row
            purchasing_id="9"
            purchaser_id="7"
            creation_time="-98*24*60*60*1000"
            total_purchased_price="1714500"/>
        <row
            purchasing_id="10"
            purchaser_id="8"
            creation_time="-100*24*60*60*1000"
            total_purchased_price="1602000"/>
        <row
            purchasing_id="11"
            purchaser_id="8"
            creation_time="-99*24*60*60*1000"
            total_purchased_price="2118000"/>
        <row
            purchasing_id="12"
            purchaser_id="8"
            creation_time="-98*24*60*60*1000"
            total_purchased_price="1775000"/>
        <row
            purchasing_id="13"
            purchaser_id="9"
            creation_time="-100*24*60*60*1000"
            total_purchased_price="1696500"/>
        <row
            purchasing_id="14"
            purchaser_id="9"
            creation_time="-99*24*60*60*1000"
            total_purchased_price="1873500"/>
        <row
            purchasing_id="15"
            purchaser_id="9"
            creation_time="-98*24*60*60*1000"
            total_purchased_price="1597500"/>
        <row
            purchasing_id="16"
            purchaser_id="10"
            creation_time="-100*24*60*60*1000"
            total_purchased_price="1155000"/>
        <row
            purchasing_id="17"
            purchaser_id="10"
            creation_time="-99*24*60*60*1000"
            total_purchased_price="1404000"/>
        <row
            purchasing_id="18"
            purchaser_id="10"
            creation_time="-98*24*60*60*1000"
            total_purchased_price="1851000"/>
    </data>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/administrator_role_mapping.xml
<?xml version="1.0"?>
<table 
name="administrator_role_mapping"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key>
            <foreign-key reference="user">
                <column name="user_id" type="long"/>
            </foreign-key>
            <foreign-key reference="role">
                <column name="role_id" type="long"/>
            </foreign-key>
        </primary-key>
    </schema>
    <data>
        <row user_id="2" role_id="1"/>
        <row user_id="3" role_id="1"/>
        <row user_id="4" role_id="1"/>
        <row user_id="5" role_id="1"/>
        <row user_id="2" role_id="2"/>
        <row user_id="6" role_id="2"/>
        <row user_id="7" role_id="2"/>
        <row user_id="8" role_id="2"/>
        <row user_id="9" role_id="2"/>
        <row user_id="10" role_id="2"/>
        <row user_id="11" role_id="3"/>
        <row user_id="12" role_id="3"/>
        <row user_id="13" role_id="3"/>
        <row user_id="14" role_id="4"/>
        <row user_id="15" role_id="4"/>
        <row user_id="16" role_id="4"/>
        <row user_id="17" role_id="4"/>
        <row user_id="18" role_id="4"/>
        <row user_id="19" role_id="4"/>
        <row user_id="20" role_id="4"/>
    </data>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/preferential_action.xml
<?xml version="1.0"?>
<table 
name="preferential_action"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key sequence="preferential_action_id_seq">
            <column name="preferential_action_id" type="long"/>
        </primary-key>
        <foreign-key reference="order_item">
            <column name="order_item_id" type="long"/>
        </foreign-key>
        <column name="matched_count" type="int"/>
        <column name="threshold_type" type="int"/>
        <column name="action_type" type="int"/>
        <column name="threshold_quantity" type="int?"/>
        <column name="threshold_money" type="decimal?"/>
        <column name="percentage_factor" type="int?"/>
        <column name="reduced_money" type="decimal?"/>
        <foreign-key reference="product">
            <column name="gift_product_id" type="long?"/>
        </foreign-key>
        <column name="gift_quantity" type="int?"/>
        <column name="total_reduced_money" type="decimal"/>
        <column name="total_gift_money" type="decimal"/>
    </schema>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/product_purchaser_mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<table name="product_purchaser_mapping" 
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key>
            <foreign-key reference="product">
                <column name="product_id" type="long"/>
            </foreign-key>
            <foreign-key reference="user">
                <column name="purchaser_id" type="long"/>
            </foreign-key>
        </primary-key>
    </schema>
    <data>
        <row product_id="108" purchaser_id="7"/>
        <row product_id="108" purchaser_id="8"/>
        <row product_id="108" purchaser_id="9"/>
    </data>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/role.xml
<?xml version="1.0"?>
<table 
name="role"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key sequence="role_id_seq">
            <column name="role_id" type="long"/>
        </primary-key>
        <column name="version" type="int"/>
        <unique>
            <column name="name" type="string[50]"/>
        </unique>
    </schema>
    <data>
        <row 
            role_id="1"
            version="1"
            name="product-manager"/>
        <row 
            role_id="2"
            version="1"
            name="purchase-commissioner"/>
        <row 
            role_id="3"
            version="1"
            name="order-dispatcher"/>
        <row 
            role_id="4"
            version="1"
            name="deliveryman"/>
    </data>
</table>

=== babyfish-ct/babyfishdemo-war3shop/install/db-installer/data/order.xml
<?xml version="1.0"?>
<table 
name="order"
xmlns="http://www.babyfishdemo.org/war3shop/db-installer" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.babyfishdemo.org/war3shop/db-installer table.xsd">
    <schema>
        <primary-key sequence="order_id_seq">
            <column name="order_id" type="long"/>
        </primary-key>
        <column name="version" type="int"/>
        <column name="gc_threshold" type="timestamp?"/>
        <column name="creation_time" type="timestamp?"/>
        <column name="delivered_time" type="timestamp?"/>
        <foreign-key reference="user">
            <column name="customer_id" type="long"/>
        </foreign-key>
        <foreign-key reference="user">
            <column name="deliveryman_id" type="long?"/>        
        </foreign-key>
        <column name="total_expected_money" type="decimal"/>
        <column name="total_reduced_money" type="decimal"/>
        <column name="total_gift_money" type="decimal"/>
        <column name="total_actual_money" type="decimal"/>
        <!-- Can be null, but it should not be null when creation_time is not null -->
        <column name="phone" type="string[20]?"/>
        <!-- Can be null, but it should not be null when creation_time is not null -->
        <column name="address" type="string[100]?"/>
    </schema>
</table>
